name: Sample pipeline

on:
  push:
    branches: main

jobs:
  node-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies..
        run: npm ci
      - name: npm building...
        run: npm run build
      - name: npm testing..
        run: echo "runned tests.."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List dir of dist
        run: cd dist
      - name: viewing..
        run: dir
      - name: Go back to org dir
        run: cd ..

  build-docker-image:
    needs: node-build-test
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
            ls ${{ github.workspace }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jawahar6/restaurant_demo_node_app:$(date +%s)
      - name: listing images
        run: docker image ls
      - name: docker push
        run: echo "pushing into docker hub"
  push-to-cloud:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: push to cloud
        run: echo "publishing it to zeet cloud"

