name: Sample pipeline

on:
  push:
    branches: main
    


jobs:
  node-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies..
        run: npm ci
      - name: npm building... 
        run: npm run build --if-present
      - name: npm testing..
        run: echo "runned tests.."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
    
  build-docker-image:
    needs: node-build-test
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: echo "building docker image"
      - name: docker push
        run: echo "pushing into docker hub"
  push-to-cloud:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: push to cloud
        run: echo "publishing it to zeet cloud"
 
